info:
  component: Platform Sample Backend
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

server:
  port: 7080

logging:
  level: INFO

logging:
  level:
    com:
      netflix: WARN